### ISSUE TITLE
ComboBox is hiding elements below from being clicked/focused

### ISSUE THREAD

**Issue by MasterKolka** [migueldeicaza/gui.cs#1584] opened 2022-02-01 14:14 UTC
ComboBox is hiding elements below from being clicked/focused after it shows a list of items once.

In the example below after opening a ComboBox list it will be impossible to focus to the TextField by mouse. Only using a keyboard.
Example:

```
var lbComboBox = new Label ("ComboBox") {
ColorScheme = Colors.TopLevel,
X = Pos.Right (lbListView) + 1,
Width = Dim.Percent(40)
};

var comboBox = new ComboBox () {
X = Pos.Right (listview) + 1,
Y = Pos.Bottom (lbListView) + 1,
Height = Dim.Fill (2),
Width = Dim.Percent(40)
};
comboBox.SetSource (items);

comboBox.SelectedItemChanged += (ListViewItemEventArgs text) => lbComboBox.Text = items[comboBox.SelectedItem];
Win.Add (lbComboBox, comboBox);
Win.Add (new TextField { X = Pos.Right (listview) + 1, Y = Pos.Top (comboBox) + 3, Height = 1, Width = 20});
```

**Comment by tznind** [comment] 2022-02-01 14:49
I can confirm this in the main branch of the repo by editing the UICatalog scenario `ListsAndCombos.cs` by adding:

```csharp
var textBox = new TextField () {
				X = Pos.Left (comboBox),
				Y = Pos.Bottom (lbListView) + 2,
				Width = 10
			};
			Win.Add (textBox);
```

Here is the diff that shows exactly where to add the code to test it:
```
PS Z:\Repos\guimain\gui.cs> git diff
diff --git a/UICatalog/Scenarios/ListsAndCombos.cs b/UICatalog/Scenarios/ListsAndCombos.cs
index ed06a66..e09ed85 100644
--- a/UICatalog/Scenarios/ListsAndCombos.cs
+++ b/UICatalog/Scenarios/ListsAndCombos.cs
@@ -83,6 +83,13 @@ namespace UICatalog.Scenarios {
                        comboBox.SelectedItemChanged += (ListViewItemEventArgs text) => lbComboBox.Text = items[comboBox.SelectedItem];
                        Win.Add (lbComboBox, comboBox);

+                       var textBox = new TextField () {
+                               X = Pos.Left (comboBox),
+                               Y = Pos.Bottom (lbListView) + 2,
+                               Width = 10
+                       };
+                       Win.Add (textBox);
+
                        var scrollBarCbx = new ScrollBarView (comboBox.Subviews [1], true);

                        scrollBarCbx.ChangedPosition += () => {
```

Not sure about the fix but definetly related to overlapping controls.  ComboBox is wierd because its size is the full dropdown area even though it renders as a single line when not dropped down.

**Comment by tznind** [comment] 2022-02-01 15:08
A fix looks like adding `this.SuperView?.SendSubviewToBack (this);` to the ComboBox `HideList` method.  This mirrors the logic in `ShowList` which calls `BringSubviewToFront`.  @BDisp  does this seem like a sensible solution? is there anything that could go wrong with this fix or do you want me to create a PR for it?

![image](https://user-images.githubusercontent.com/31306100/151994124-955a1820-b592-417f-976c-972b2f3d869c.png)

**Comment by tznind** [comment] 2022-02-01 15:20
The above fix only works when collapsing the ComboBox with the mouse (on the down dropdown).  Selecting from the dropdown with Enter does not call `HideList`.  I think we should add that call in under this circumstances too.

I think `private void Selected ()` needs to be updated to call `HideList` too.

**Comment by MasterKolka** [comment] 2022-02-01 15:24
Maybe it could be a good idea to dynamically change height of the ComboBox when it opens/closes. Then it won't overlap anything.

**Comment by BDisp** [comment] 2022-02-01 15:58
That fix it @tznind. Thanks. A better implementation of this is to add/remove the `ListView` to the `ComboBox` superview, like the `Autocomplete` now does, outside. This way allows it to popup the dropdown on available space on down/up/left/right.

**Comment by MasterKolka** [comment] 2022-02-02 07:30
It also will be good to have whole combobox clickable instead an arrow only. Thanks.

**Comment by tznind** [comment] 2022-02-02 09:22
> It also will be good to have whole combobox clickable instead of an arrow only. Thanks.

Clicking in a combo box moves the cursor into the text box and allows you to type free text into the combo box.  It also lets you drag a text selection e.g. to copy the text you have pasted into the ComboBox.  Are you unable to do this? Or did you mean for the click to expand the list? I think if you register your own mouse handler you should be able to alter the default behaviour.

**Comment by BDisp** [comment] 2022-02-02 11:58
> It also will be good to have whole combobox clickable instead of an arrow only. Thanks.

I know what you mean. Initially the author of this view only pretended to use a searchable `ListView` to use in a `Dialog`, with the `ListView` always opened. So I suggested that this can be working as a dropdown combobox. The reason for it only has a minimum of one clickable line, is defined by a variable for the combobox having of a minimum height of two (one for `TextField` and one for `ListView`) and was implemented a `AutoHide` property. The dropdown height is defined by the `ComboBox` height.
It have so much work for to be improved.

**Comment by BDisp** [comment] 2022-02-02 12:02
> @tznind It will be better to UX. Opening a combobox by clicking on it is a default behavior for almost all UI frameworks.
Like here - https://mdbootstrap.com/snippets/jquery/mdbootstrap/921549

There is one thing that I don't like in the sample, which is the drop list hiding the combobox.

**Comment by MasterKolka** [comment] 2022-02-02 12:07
It was implemented that way to be able to open upside.
![image](https://user-images.githubusercontent.com/29628534/152150670-f9dcddbe-4ae7-422a-9808-1e457a269086.png)

**Comment by BDisp** [comment] 2022-02-02 12:13
I agree, as you can see in my comment https://github.com/migueldeicaza/gui.cs/issues/1584#issuecomment-1027001460. But the popup could open from the top of the ComboBox and not from the bottom.

**Comment by tznind** [comment] 2022-02-02 12:58
These sound like great improvements.  Having code reuse between AutoComplete and the ComboBox would be nice too since it is basically the same thing (an overlay that spills out of the controls bounds).  

I think we should still keep the PR to fix the overlay bug at least until a more comprehensive refactor of ComboBox (as described in this issue) is ready.

**Comment by BDisp** [comment] 2022-02-02 13:01
> I think we should still keep the PR to fix the overlay bug at least until a more comprehensive refactor of ComboBox (as described in this issue) is ready.

I completely agree with you.

**Comment by MasterKolka** [comment] 2022-02-02 14:20
Another problems:
1) It is impossible to programmatically select an item
2) It is impossible to assign another collection to the same combobox if currently selected item number is higher than amount of items in a new collection

**Comment by BDisp** [comment] 2022-02-02 18:53
> Another problems:
> 
>     1. It is impossible to programmatically select an item
> 
>     2. It is impossible to assign another collection to the same combobox if currently selected item number is higher than amount of items in a new collection

@tznind I made a fix for this. You can copy and paste or do whatever you want. Thanks. https://github.com/BDisp/gui.cs/tree/combofix-continuation

**Comment by tznind** [comment] 2022-02-03 06:36
Thanks, I have added it to the PR

**Closed** 2022-02-06 22:44 UTC
