### ISSUE TITLE
Either mouse or keyboard does not work on windows console

### ISSUE THREAD

**Issue by moroslantia** [migueldeicaza/gui.cs#96] opened 2018-05-20 10:34 UTC
I tried to use the component within windows.
When i recreate the example (with packages from nuget) and i start it out from VisualStudio i can work with the mouse but keyboard does not (sometimes the first keyboard stroke works)

When i run the example from cloned source (out from cmd window with dotnet run), the keyboard inputs work, but when i want to use the mouse, the window console switches to text selection mode. The mouse coordinates are not displayed in the window.

Do i miss something?

**Comment by migueldeicaza** [comment] 2018-05-21 14:16
Are you using the latest nuget?   The sample on github might not reference the latest nuget

**Comment by migueldeicaza** [comment] 2018-05-21 16:51
Ok that looks like I will need to debug the new Windows driver, will do that when I am back at home (where my Windows machine is).   Likely Wednesday or Thursday night.

In the meantime, can you describe what language your keyboard is, and what evrsion of the OS, which runtime (.NET Framework, .NET Core) and steps to reproduce?

**Comment by moroslantia** [comment] 2018-05-21 17:28
Sure. Thanks for your help.
Keyboard: German or English layout
OS: Windows 10, 1703

With nuget package 0.12.0
Runtime: .Net Core 2.0
Reproduce:
- New Console Project (.net Core)
- Install Nuget Terminal.gui
- Copy and Paste code from gui.cs / Example / demo.cs
- start debug session
- First keyboard stroke get's recognized, but no follow up
Remark: in the console window -> Properties -> Quick Edit Mode has to be deselected 

With git repository clone:
Example Project (with .Net 4.6.1) can't get started (after start the debugger stops with: 
An unhandled exception of type 'System.IO.FileLoadException' occurred in Unknown Module.)

StandaloneExample (start with dotnet run)
Runtime: .Net Core 2.0
Reproduce: 
- goto folder StandaloneExample
- run "dotnet run"
- mouse events not shown in the terminal, no reaction to any mouse action
- Keyboard strokes are recognized 
Remark: in the console window -> Properties -> Quick Edit Mode has to be deselected 

Hope this helps.

**Comment by migueldeicaza** [comment] 2018-05-25 23:04
Hello,

I attempted the first, and was not able to reproduce (fresh package, install, run with NET Core).

I attempted the second one, and do not get it either, I would need a stack trace to diagnose what the issue is.

I attempted the third one and the mouse works fine - both with Quick Edit Mode on and off.

**Comment by migueldeicaza** [comment] 2018-06-05 04:09
closing

**Closed by migueldeicaza** 2018-06-05 04:09 UTC

**Comment by fcallejon** [comment] 2018-06-07 08:44
Hi, sorry to post again here, but I'm having a similar issue.
For me only the keyboard doesn't work. (I'm not sure if open a new issue was worth)

Microsoft Visual Studio Community 2017 
```
Version 15.7.3
VisualStudio.15.Release/15.7.3+27703.2026
Microsoft .NET Framework
Version 4.7.02558
Installed Version: Community

C# Tools   2.8.3-beta6-62923-07. Commit Hash: 7aafab561e449da50712e16c9e81742b8e7a2969
Visual Studio Code Debug Adapter Host Package   1.0
```

CsProj info: 
```
<ProductVersion>8.0.30703</ProductVersion>
<OutputType>Exe</OutputType>
<TargetFrameworkVersion>v4.6.2</TargetFrameworkVersion>
```

Terminal.Gui Package:
`<package id="Terminal.Gui" version="0.13.0" targetFramework="net462" />`

Windows:
```
Version:  10 Pro (1703)
Os Build: 15063.1088 
```

Keyboard: English / Ireland

Steps:

1. Add nuget package to existing project
2. Copy code from [demo.cs](https://github.com/migueldeicaza/gui.cs/blob/master/Example/demo.cs) into Program.cs
3. Fix `using` issues
4. Run

Let me know if you need something else.
I'll try to debug it in the weekend (with Terminal.Gui src).

**Comment by fcallejon** [comment] 2018-06-07 08:50
Playing with console options found that when "Use Legacy console" is checked it works fine.
