### ISSUE TITLE
Bug: TextView doesn't work on Windows/.NET Core -> crashes almost immediately

### ISSUE THREAD

**Issue by RednibCoding** [migueldeicaza/gui.cs#214] opened 2019-05-29 10:53 UTC
using Terminal.Gui;

	class Program
	{
		static void Main()
		{
			Application.Init();
			var top = Application.Top;

			var win = new Window("App")
			{
				X=0,
				Y=1,
				Width=Dim.Fill(),
				Height=Dim.Fill()
			};
			top.Add(win);

			var textView = new TextView()
			{
				X=0,
				Y=2,
				Width=40,
				Height=40
			};

			win.Add(textView);

			Application.Run();
		}
	}

This code causes the app to crash as soon as you clicking in the console or want to type a character.

Error is:

> ->Application.Run(): System.ArgumentOutOfRangeException: "Index was out of range. Must be non-negative and less than the size of the collection."

**Comment by migueldeicaza** [comment] 2019-05-30 03:00
I could not reproduce this on Unix.

Would you mind trying this from Visual Studio and finding out where it is crashing?

**Comment by RednibCoding** [comment] 2019-06-05 07:27
It is crashing when calling the Run method:

`// Zusammenfassung:
//     Runs the application with the built-in toplevel view

public static void Run();`

**Comment by fubar-coder** [comment] 2019-06-17 14:49
Stack trace:

```text
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
  at at System.Collections.Generic.List`1.get_Item(Int32 index)
  at at Terminal.Gui.TextModel.GetLine(Int32 line)
  at at Terminal.Gui.TextView.GetCurrentLine()
  at at Terminal.Gui.TextView.MouseEvent(MouseEvent ev)
  at at Terminal.Gui.Application.ProcessMouseEvent(MouseEvent me)
  at at Terminal.Gui.WindowsDriver.Mono.Terminal.IMainLoopDriver.MainIteration()
  at at Mono.Terminal.MainLoop.MainIteration()
  at at Terminal.Gui.Application.RunLoop(RunState state, Boolean wait)
  at at Terminal.Gui.Application.Run(Toplevel view)
  at at Terminal.Gui.Application.Run()
  at TestGuiCs.Program.Main(String[] args) in D:\Test-Projekte\TestGuiCs\TestGuiCs\Program.cs:33
```

**Comment by angrywasp** [comment] 2019-07-29 07:33
GetLine throws an IndexOutOfRange exception when trying to get a line when no text has been set on the control. The lines collection is empty. Setting the Text property of the control to an empty string when instantiating the control works around the issue

**Comment by tig** [comment] 2020-06-04 03:59
No repro. Closing.

**Closed by tig** 2020-06-04 03:59 UTC
Labels: bug
