### ISSUE TITLE
Emojis not working in TableView? (NStack or gui.cs issue potentially)

### ISSUE THREAD

**Issue by kierenj** [migueldeicaza/gui.cs#1522] opened 2021-11-26 00:06 UTC
I get this exception from `NStack`:
````
System.ArgumentException: Value in the surrogate range and isn't part of a surrogate pair!
   at System.Rune..ctor(Char ch)
   at System.Rune.op_Implicit(Char ch)
   at Terminal.Gui.TableView.<>c.<CalculateMaxCellWidth>b__92_1(Char c) in C:\git\saffron\deps\gui.cs\Terminal.Gui\Views\TableView.cs:line 1123
   at System.Linq.Enumerable.Sum[TSource](IEnumerable`1 source, Func`2 selector)
   at Terminal.Gui.TableView.CalculateMaxCellWidth(DataColumn col, Int32 rowsToRender, ColumnStyle colStyle) in C:\git\saffron\deps\gui.cs\Terminal.Gui\Views\TableView.cs:line 1123
   at Terminal.Gui.TableView.CalculateViewport(Rect bounds, Int32 padding)+MoveNext() in C:\git\saffron\deps\gui.cs\Terminal.Gui\Views\TableView.cs:line 1081
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Terminal.Gui.TableView.Redraw(Rect bounds) in C:\git\saffron\deps\gui.cs\Terminal.Gui\Views\TableView.cs:line 200
````

The data in the `TableRow` column contains the emojis, `🤖🧠`.

The "offending" line of code is:

`spaceRequired = Math.Max (spaceRequired, GetRepresentation (Table.Rows [i] [col], colStyle).Sum (c => Rune.ColumnWidth (c)));`

My guess is, this code is assuming a single `char` is a valid `Rune`, which is not always true. Should/could it instead use `DecodeRune` in a loop, calling `Rune.ColumnWidth` on each and summing the results?

Or, is this kind of emoji/data not supported on gui.cs and I should avoid? Thanks.

**Comment by BDisp** [comment] 2021-11-26 00:13
Can you try with my PR #https://github.com/migueldeicaza/NStack/pull/54, please?

**Comment by kierenj** [comment] 2021-11-26 00:13
Ah... there are a few places with this kind of code:
![image](https://user-images.githubusercontent.com/82343/143509467-fa349e15-43fd-4d5f-9691-4584032b9c29.png)
...and others still checking `char` widths with this method.

Maybe a new method in `NStack`... `Rune.CharColumnWidth(char)` ?

**Comment by kierenj** [comment] 2021-11-26 00:15
Aha! `public static int ColumnWidth(char c)` in that PR :) :)

I'll try it, thanks

**Comment by kierenj** [comment] 2021-11-26 13:13
It no longer crashes, but the emojis do not render correctly and everything is misaligned:

![image](https://user-images.githubusercontent.com/82343/143586458-2686d04a-a073-48a4-808d-5f19aa72da65.png)

**Comment by BDisp** [comment] 2021-11-26 17:23
Thanks for your efforts. I would like to know which driver did you used, the font type and terminal, please.

**Comment by kierenj** [comment] 2021-11-26 18:07
That's the Windows driver, on Windows Terminal, font is `MesloLGL NF`

(https://github.com/romkatv/dotfiles-public/tree/master/.local/share/fonts/NerdFonts)

**Comment by BDisp** [comment] 2021-11-27 13:49
Really there is a big fault in `WindowsDriver` and `NetDriver` because they are adding each `Rune` or `Char` to each column. The problem is that only one column could be a combination of two `Rune` or `Char`. With valid surrogate pairs there is no problems because they will return a `Rune` or `Char` from `0x10000 to 0x10FFFF`. But without valid surrogate pairs there is some combinations of two `Rune` or `Char` that result on a `String` with only one column. One example is the combination of the string `"\u0065\u0301"` which contains two `Rune` or `Char` ('e' and '´'), resulting in the string "é", differently of "é". If you press the delete key on the resulting string it will delete the '´' first and you need to press the delete key again to delete the 'e'. On the other hand, if you press the delete key on the other differently `Rune` or `Char`, it will delete the whole 'é'. This the reason why the string `"Misérables"` is printed as` "Mise´rables"` in the "`TableEditor.cs`" and in the "`TabViewExample.cs`" scenarios.
Therefore, the `int [,,] Contents` property isn't the proper type to save the value and also the `OutputBuffer [position].Char.UnicodeChar = (char)rune` on `WindowsDriver`.
With the `CursesDriver` may be more easier to get a solution to this because the buffer is sent as string with the function `Curses.addwstr`.
Also with the `NetDriver` may could be done.
With `WindowsDriver` may be more difficult because it may not support writing the string to the buffer.
Gurus, we will needed all help as possible to try solving all of this, thanks.

**Comment by BDisp** [comment] 2021-11-27 23:20
This can be fixed by using the `String.Normalize()` method;
```cs
("Les Mise" + Char.ConvertFromUtf32(Int32.Parse("0301", NumberStyles.HexNumber)) + "rables").Normalize()
```

**Comment by BDisp** [comment] 2021-11-28 02:09
With the `VsDebugConsole` it's rendered well with the `MesloLGL NF` font.

![vsdebugconsole](https://user-images.githubusercontent.com/13117724/143726137-cb0ccc32-6302-4751-810a-95e313e91f4a.png)

With `Windows Terminal` isn't rendered well. So I think it's some issue with `Windows Terminal` itself.

![windows-terminal](https://user-images.githubusercontent.com/13117724/143726158-2a525c4e-3497-4b79-8325-3736448100f9.png)

**Comment by BDisp** [comment] 2021-11-28 02:34
With `VSCode` `"integratedTerminal"` also not rendering well, with the aggravating of the mouse not working too.

![vscode-integratedTerminal](https://user-images.githubusercontent.com/13117724/143726638-e0f72cfa-2bfc-44ef-8111-bda3b6416256.png)

**Comment by BDisp** [comment] 2021-11-28 02:51
> Also with the `NetDriver` may could be done.
> With `WindowsDriver` may be more difficult because it may not support writing the string to the buffer.
> Gurus, we will needed all help as possible to try solving all of this, thanks.

There is no need to change anything because all what is needed is to use the `Normalize` method, only when inserting chars combinations that can be joined, like "Mise´rables".

**Comment by BDisp** [comment] 2021-11-29 12:35
Does anyone know why is appearing black square? This is happening with `Ubuntu` running on `VirtualBox`.

![ubuntu-vbox-black-print](https://user-images.githubusercontent.com/13117724/143869057-5bc3002f-9d21-41d7-9675-9fe6c35c4f42.gif)

**Comment by BDisp** [comment] 2021-11-29 14:26
> Maybe a new method in `NStack`... `Rune.CharColumnWidth(char)` ?

The `Rune` struct already implemented implicit operators that does that conversion automatically.

**Comment by tig** [comment] 2022-05-28 23:20
@tznind - do you think this is resolved with all the great work @BDisp did on wide Rune support?

**Comment by tznind** [comment] 2022-06-02 14:13
Yes I think this should now be completely resolved by @BDisp  rune work:

![image](https://user-images.githubusercontent.com/31306100/171649450-f08d7347-8ebd-461d-889e-2f3972751bba.png)

**Closed** 2022-06-02 21:13 UTC
Labels: bug
