### ISSUE TITLE
Change the font size and color

### ISSUE THREAD

**Issue by GabrielCosta-stack** [migueldeicaza/gui.cs#1674] opened 2022-04-18 16:18 UTC
Hi, I am trying to learn about this library(gui.cs), I can't figure out how to change the font size and color of the Label. Can anyone help, thanks.

Best regards

**Comment by BDisp** [comment] 2022-04-18 16:41
The font size is only possible change on the properties or definition of the console/terminal.
For the color on label see this discussion (https://github.com/migueldeicaza/gui.cs/discussions/1667#discussioncomment-2579893).

**Comment by tznind** [comment] 2022-04-18 17:18
`ColorScheme` is used to control colors because it allows you to specify what color to use under a veriety of situations (i.e. Normal, when Focused, when Disabled etc)

**Comment by GabrielCosta-stack** [comment] 2022-04-19 06:21
@BDisp Thanks for the quick answer, so I can assume that it is not possible to have labels with different font sizes. Since the font size depends on the terminal settings. Or am I wrong?

**Comment by tznind** [comment] 2022-04-19 08:09
> so I can assume that it is not possible to have labels with different font sizes. Since the font size depends on the terminal settings. Or am I wrong?

That is correct.  Although theres always ASCII art: 

```
 /  \ / )( \  ( \/ )(  __) / _\ / )( \
(  O )) __ (   )  /  ) _) /    \) __ (
 \__/ \_)(_/  (__/  (____)\_/\_/\_)(_/
```

```
____ _  _    _   _ ____ ____ _  _ 
|  | |__|     \_/  |___ |__| |__| 
|__| |  |      |   |___ |  | |  | 
                                  
```

**Comment by tig** [comment] 2022-04-19 18:02
Not a bug. Closing.

**Closed by tig** 2022-04-19 18:02 UTC
Labels: question
