### ISSUE TITLE
Mouse Clicks are not processing quickly (requiring double click on button)

### ISSUE THREAD

**Issue by tig** [migueldeicaza/gui.cs#1848] opened 2022-07-04 15:26 UTC
After merging #1807 Buttons require double click (Windows Terminal, WindowsDriver)

**Comment by tig** [comment] 2022-07-04 15:28
Actually, listbox too?!?!

**Comment by tig** [comment] 2022-07-04 15:32
Weird. In this vid I'm clicking all over the place, pausing for several seconds... Eventually (sometimes) the click gets processed. But there's a several second delay and sometimes they don't process at all.

![zpdOaGD 1](https://user-images.githubusercontent.com/585482/177184837-b44c445a-ce1a-4966-9a9a-6fa0e59ad70b.gif)

**Comment by tznind** [comment] 2022-07-04 15:35
What does the Mouse scenario show?

**Comment by BDisp** [comment] 2022-07-04 15:38
I can confirm this but only with the Windows Terminal and also without the last PR merged.

**Comment by BDisp** [comment] 2022-07-04 15:40
> What does the Mouse scenario show?

It's only returns ButtonPressed and ButtonReleased, so some bug with the Windows Terminal. I'll check.

**Comment by BDisp** [comment] 2022-07-04 16:39
With the `VSConsoleDebugger` and `cmd` a click event is generated by these three commands:
```
X:23;Y:11;ButtonState:Button1Pressed;EventFlags:0
X:23;Y:11;ButtonState:0;EventFlags:0
X:23;Y:11;ButtonState:0;EventFlags:MouseMoved
```
1 - The pressed button.
2 - Released button.
3 - An extra command that allow to fire the clicked event.


The `Windows Terminal` is only returning two commands, the pressed and the released. The clicked only will be fired after some mouse move. So, I can't do nothing to fix this without the extra command.
```
X:33;Y:13;ButtonState:Button1Pressed;EventFlags:0
X:33;Y:13;ButtonState:0;EventFlags:0
```

**Comment by BDisp** [comment] 2022-07-04 16:45
> After merging #1807 Buttons require double click (Windows Terminal, WindowsDriver)

I hope you do not believe this happened due to the merging of my PR, do you?

**Comment by tig** [comment] 2022-07-04 23:01
> > After merging #1807 Buttons require double click (Windows Terminal, WindowsDriver)
> 
> I hope you do not believe this happened due to the merging of my PR, do you?

No. I just went back to `3810049` and it still repos.

If I go back to `c58a6b2` it works fine.

<img width="519" alt="image" src="https://user-images.githubusercontent.com/585482/177223706-dfd3dc24-4655-4854-9b54-0dced0b5b45d.png">

It appears the problem was introduced by this:

<img width="514" alt="image" src="https://user-images.githubusercontent.com/585482/177223770-98a01b24-eb51-47d6-92ce-1a471d606bd0.png">

**Comment by tig** [comment] 2022-07-04 23:05
I tested by just reverting `893220b2` and it works fine. So you broke it with #1840.

**Comment by BDisp** [comment] 2022-07-04 23:10
> I tested by just reverting `893220b2` and it works fine. So you broke it with #1840.

Sorry about that, I intended to fix an expected clicked event even it's wasn't pressed and released on the same point. But probably I already did that changes because the clicked event wasn't be fired before from Windows Terminal. I'll check again.

**Comment by BDisp** [comment] 2022-07-05 11:38
@tig is there a way to immediately starting debugging from `Visual Studio 2022` with `Windows Terminal`, without attaching it later?

**Comment by tznind** [comment] 2022-07-05 11:49
> @tig is there a way to immediately starting debugging from `Visual Studio 2022` with `Windows Terminal`, without attaching it later?

If you go to Solution and right click and 'Add Existing Project' you can add an executable.  Then right click it and set it as startup project.   It will wind up looking like this:

![image](https://user-images.githubusercontent.com/31306100/177320414-26495a5e-f9ea-454f-8c15-06ef202341cd.png)

Then right click it and go to Properties and set some Arguments e.g. `c:\source\gui.cs\UICatalog\dotnet run`

**Comment by BDisp** [comment] 2022-07-05 12:50
> Then right click it and go to Properties and set some Arguments e.g. `c:\source\gui.cs\UICatalog\dotnet run`

Thanks @tznind for the information. I was unaware of that. I still haven't gotten what I want but I won't give up.

**Comment by BDisp** [comment] 2022-07-05 12:54
> I noticed recently on my Win11 & VS2022 build Win Term is the default console used for VS debugging sessions. IIRC, I changed some settings to make Windows Terminal default, but I don't remember the details.

@tig I also have Win11 & VS2022, and if you find out the details of the settings, I thanked you to share it. Thanks.

**Comment by tig** [comment] 2022-07-05 12:58
In Win Terminal settings:

<img width="864" alt="image" src="https://user-images.githubusercontent.com/585482/177333167-4cd098d3-75c1-4bb2-8658-d34447e6dfe5.png">

**Comment by BDisp** [comment] 2022-07-05 13:43
@tznind I get this error and the console opens and closes immediately. I think I'm failing with some setting.
```
Exception thrown at 0x00007FFDA59C474C (KernelBase.dll) in powershell.exe: 0xE0434352 (parameters: 0xFFFFFFFF80131501, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x00007FFD8F9E0000).
'powershell.exe' (Win32): Loaded 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\diasymreader.dll'. 
```

**Closed** 2022-07-05 13:50 UTC
Labels: bug

**Comment by BDisp** [comment] 2022-07-05 14:14
It's working with any of the following arguments attached to the debugger but the breakpoints will not currently be hit. No symbols loaded for this document. Do you have any solution?

`dotnet run --project c:\source\gui.cs\UICatalog\`

`dotnet c:\source\gui.cs\UICatalog\\bin\Debug\net6.0\UICatalog.dll`

**Comment by BDisp** [comment] 2022-07-05 14:27
Another detail I'm checking is that in fact it does not open `Powershell`, but the `VsDebugConsole.exe` running the powerrshell that in turn runs `UICatalog`. It really doesn't seem to be what I want. But thanks anyway for the tip.

**Comment by BDisp** [comment] 2022-07-05 16:42
I already managed to open on `Windows Terminal` but without debugging. In `launchSettings.json` I added the follow:

```
    },
    "Win Term": {
      "commandName": "Executable",
      "executablePath": "wt.exe",
      "commandLineArgs": "dotnet ./UICatalog/bin/Debug/net6.0/UICatalog.dll",
      "workingDirectory": ".."
    }

```

**Comment by BDisp** [comment] 2022-07-05 17:01
For `Ubuntu` distro that also opens on the `Windows Terminal` but without debugging too:

```
    },
    "Ubuntu": {
      "commandName": "Executable",
      "executablePath": "ubuntu.exe",
      "commandLineArgs": "-c dotnet ./UICatalog/bin/Debug/net6.0/UICatalog.dll",
      "workingDirectory": ".."
    },
```
