### ISSUE TITLE
How to get a "terminal view"? 

### ISSUE THREAD

**Issue by buretto** [migueldeicaza/gui.cs#1404] opened 2021-07-29 21:06 UTC
Is there a simple way to have an embedded terminal like view?

My goal is to have a console app with multiple panes.
One for input commands, one for command outputs, and one for logs.
It'll also have more to GUI, but the whole premise stems from input coming from console-like string commands.
e.g. User types text, a "process command" event fires when return input is sent, this event then parses and validates command, etc..

Maybe it's best described visually, so here is how my GUI looks currently:
[image](https://i.gyazo.com/f8db09009f90aaedc3b8787024687b4c.png)

I wonder if there is already a solution available I could use.

Currently I am trying to accomplish this by extending from TextView because I couldn't find any examples of such a thing.
I wonder if I'm misunderstanding something, or how nobody (based off what I could find on the web) has seemed to require something like this ? I have simple functionality where I create a class inheriting from TextView, and override `ProcessKey` and do various things to sort of get the desired functionality, but I can see it's probably not leading towards a robust solution.

I recently found out about xTermSharp's `TerminalView`, I think it could maybe be what I'm looking for?  Unfortunately I couldn't get it working. The readme states:

> In addition, a complete Xterm/Vt100 terminal emulator that you can embed is now part of XtermSharp - you just need to pull TerminalView.cs into your project.

But to my understanding, because TerminalView.cs relies on XtermSharp, I pull that too right? In my case I cloned the whole repo and tried building and running the GuiCsHost project. I fixed a bit of the errors related to syntax changes that weren't updated yet (that file seems a bit undermaintained), so I got it to build but now at runtime I'm facing even more errors which are leading me to believe I'm doing it wrong, e.g. 

> System.DllNotFoundException: 'Unable to load DLL 'libpty.dylib': The specified module could not be found. (Exception from HRESULT: 0x8007007E)'

  at [this line](https://github.com/migueldeicaza/XtermSharp/blob/1bed529cd20748ef9da43753e8dd553f65fc5582/XtermSharp/Pty.cs#L37).  

So before I go further with this I'd like to know, is this `TerminalView` usable at the moment and could I use it for these purposes?

I thought I'd ask this, and hope to get some clarification as to whether to try getting `TerminalView` to work in my project, or try extending TextView, or to not bother completely (e.g. if I misunderstand and gui.cs is not meant for this purpose)?

I apologize for my lack of understanding, I'm just not entirely sure if my use case is a good candidate for all of these tools.

**Comment by BDisp** [comment] 2021-07-29 21:21
> My goal is to have a console app with multiple panes.

I can't help you about `TerminalView` and `XtermSharp`, but if you are looking for app with multiple panes you can try the `Toplevel.IsMdiContainer`. Look at the `BackgroundWorkerCollection.cs` on the `UICatalog` project.

**Comment by bureto** [comment] 2021-07-30 01:28
Okay thanks I took a look - am I correct in thinking the `IsMdiContainer` purpose is for facilitating the management of dynamically varying number of child top levels?

i.e. If I plan on setting the top level hierarchy on app start, and it doesn't change ever, then it should be okay to not try integrating with IsMdiContainer and related features?

**Comment by bureto** [comment] 2021-07-30 01:53
Regarding my main question about embedded terminal. 
Considering I plan on parsing command line arguments, would this be easy to work with XtermSharp (assuming I correctly understand correctly what XtermSharp overall purpose is for in the first place)? Would I be able to somehow use `System.CommandLine` or some other .NET command line parser? AFAIK you can typically just call parsing function with string array of arguments, and it will output however you have it configured (e.g. I could write to TextView). I'm not sure how default output or error handling could be done though, I think they just output the messages to console stdout. 

So all of these things make me feel like it's possible but might be a headache?
I wonder if someone else has worked on something similar and could share any advice/insights on what it takes to accomplish such a thing.

I guess I'll describe my goal in one line to help summarize:
Have an embedded terminal which works like a command line by taking in text commands and then being able to parse these commands into actions/behavior. Imagine this as having a literal bash or CMD shell embedded as a view. For example, it would look like the Input window in [this image (my current GUI)](https://i.gyazo.com/f8db09009f90aaedc3b8787024687b4c.png):

Else, if someone could explain to me the technical difficulties making this goal unfeasible that'd also be greatly appreciated. 
For now, I've got the TextView idea sort of working. The next step is to parse its input commands somehow. There's probably some thing's I haven't considered yet but maybe it'll end up being fine.

**Comment by bureto** [comment] 2021-07-30 05:49
I've been working on the TextView solution and things are looking quite promising. I guess I should say though that my needs for this are quite barebones so it'd probably not be fair to call this solution a "TerminalView" (but rather a TextView that tries to emulate the UX of a terminal).

While working on it I've come across a few small things I'd like to try and solve/implement:
1. What'd be the most elegant way to restrict the cursor's position to certain column range? I was thinking of having a check and set override mechanism in something like ProcessKeys and OnMouseEvent, but was wondering if there was some other way. For example I noticed the `LeftColumn` property which I thought might be used for this purpose but AFAICT that's for something else.
2. For my "output" `TextView`, I've specified `TextDirection.LeftRight_BottomTop`. The problem is whenever the text is changed, it sets the view (scrolls) all the way back to the top, so to see the new value the user must scroll all the way back down. How to stop this from happening?
3. I've specified `DesiredCursorVisibility = CursorVisibility.BoxFix` in the `TextView`, but it does not appear to work or do anything. 
4. In terminals it's possible to select text while also have cursor somewhere totally seperate, AFAICT this is not supported with the selection process of gui.cs (since IIRC the selection range goes based of selection start indices, towards current cursor position)?

**Comment by tznind** [comment] 2021-07-30 07:05
> What'd be the most elegant way to restrict the cursor's position to certain column range?

You should be able to disable input focusing on a view with `CanFocus=false` and you probably also want `ReadOnly=true`.

> [...] whenever the text is changed, it sets the view (scrolls) all the way back to the top

You should be able to change where the scroll point is using:

`ScrollTo (int idx, bool isRow = true)`

You can read the current scroll position with `TopRow` property so should be able to read the old scroll location, append some text then reset the old scroll position?

**Comment by bureto** [comment] 2021-07-30 07:42
Hey thanks for the ideas.

> You should be able to disable input focusing on a view with CanFocus=false and you probably also want ReadOnly=true.
I think this doesn't solve that particular problem of mine since I do actually want to still be able to focus that View. Imagine having a TextView where the left 4 columns on the first row are "untouchable", i.e. the cursor cannot move there. 

But actually funny enough I was just about to ask a similar question related to this. Would it be possible to have functionality similar to `CanFocus=false`, except it allows scrolling and perhaps selecting/highlighting? i.e. You can focus the TextView, but the cursor remains on the previous TextView where it just was. I think for something like this would probably require a custom solution. I'm thinking it could have an invisible cursor on the newly focused readonly TextView, and draw a pseudo cursor in the box where it left off. Then a hotkey in the TopView will set focus to the previous TextView on any keypress.


> You should be able to change where the scroll point is using:

This works. Is there a way to get how many lines are visible? This way I was thinking I could do `ScrollTo(textView.Lines - visibleLines)`, as I'd like it to scroll down to the bottom whenever new text is added.

**Comment by bureto** [comment] 2021-07-30 07:53
> Is there a way to get how many lines are visible? This way I was thinking I could do ScrollTo(textView.Lines - visibleLines), as I'd like it to scroll down to the bottom whenever new text is added.

        textView.ScrollTo(textView.Lines - textView.Bounds.Height);

**Comment by BDisp** [comment] 2021-07-30 13:00
> Okay thanks I took a look - am I correct in thinking the `IsMdiContainer` purpose is for facilitating the management of dynamically varying number of child top levels?
> 
Yes

> i.e. If I plan on setting the top level hierarchy on app start, and it doesn't change ever, then it should be okay to not try integrating with IsMdiContainer and related features?
>
A `Toplevel` with `IsMdiContainer` as true it only will accommodate his childs. You can do whatever you want with them before you close them.
If you don't want to use the `IsMdiContainer` as true, but only want a `Toplevel` at a time where the main will have his data preserved after closing the last `Toplevel` opened, then look at the `SingleBackgroundWorker.cs` scenario on the `UICatalog` project.

**Comment by BDisp** [comment] 2021-07-30 13:15
> Regarding my main question about embedded terminal.
> Considering I plan on parsing command line arguments, would this be easy to work with XtermSharp (assuming I correctly understand correctly what XtermSharp overall purpose is for in the first place)?

@migueldeicaza already propose doing that in the #1046. I tried to do something but i get a bunch of errors with the XtermSharp and I ended by giving up.

**Comment by bureto** [comment] 2021-07-30 16:35
Okay thanks very much for the quick help and clarification. At this point I'm almost certain that the TextView route is the way to go for me. It's simple but seems to work for what I want at least. Now I'm just trying to fix some of its things up -- will perhaps consider more ideas in the future.

For:
> I've specified DesiredCursorVisibility = CursorVisibility.BoxFix in the TextView, but it does not appear to work or do anything.

I think that the `TextView` has been made to force a certain cursor visibility which is what's causing  it.
https://github.com/migueldeicaza/gui.cs/blob/dcc126942adce4b4ffac88358e0e023ddab18c20/Terminal.Gui/Views/TextView.cs#L1230

I see this is an intentional feature explicitly set, but am wondering for what purposes / how does it work?
Why is it exclusive for TextView? Something to do with word wrapping I think, but having trouble thinking about it.
Is it possible to set TextView's `DesiredCursorVisibility` to something else?

**Comment by BDisp** [comment] 2021-07-30 16:51
> I see this is an intentional feature explicitly set, but am wondering for what purposes / how does it work?
> Why is it exclusive for TextView? Something to do with word wrapping I think, but having trouble thinking about it.
> Is it possible to set TextView's `DesiredCursorVisibility` to something else?

Who created this method in `TextView` was me with the intention that if `WordWrap` is off putting the invisible cursor if it is outside its limits. To this end, the current property is saved and restore it if the cursor can be visible. But it really has a strange behavior that I think is not related to this method. You can change it and check if another result is obtained.

**Comment by bureto** [comment] 2021-07-30 18:04
Oh okay I think I get it. So the desire is to make cursor go invisible if it goes outside the TextField's visible range by setting `DesiredCursorVisibility = CursorVisibility.Invisible`? And to do this we save the `DesiredCursorVisibility` so we can restore it later when it comes back into visible range?

If so then I think I can fix this.

**Comment by bureto** [comment] 2021-07-30 18:09
Just wanted to mention for:
>What'd be the most elegant way to restrict the cursor's position to certain column range? I was thinking of having a check and set override mechanism in something like ProcessKeys and OnMouseEvent, but was wondering if there was some other way. For example I noticed the LeftColumn property which I thought might be used for this purpose but AFAICT that's for something else.

I found this seems like a perfect solution:
```
 public override void PositionCursor()
  {
        if (CurrentColumn < 4 && CurrentRow == 0)
            CursorPosition = new Point(4, 0);
        base.PositionCursor();
  }
```

**Comment by BDisp** [comment] 2021-07-30 18:13
> Oh okay I think I get it. So the desire is to make cursor go invisible if it goes outside the TextField's visible range by setting `DesiredCursorVisibility = CursorVisibility.Invisible`? And to do this we save the `DesiredCursorVisibility` so we can restore it later when it comes back into visible range?
> 
> If so then I think I can fix this.

Not only. It also sets the cursor as underlined, because if we press the `Insert` key (`Used`), the box cursor is confused with this. I found where is the bug and I'm working on a fix now.

**Comment by BDisp** [comment] 2021-07-30 18:23
> For example I noticed the LeftColumn property which I thought might be used for this purpose but AFAICT that's for something else.

The `LeftColumn` determines the start column position at the zero position of the `View.Bounds.X`.
The `TopRow` determines the start row position at the zero position of the `View.Bounds.Y`.

**Comment by bureto** [comment] 2021-07-30 18:29
> The LeftColumn determines the start column position at the zero position of the View.Bounds.X.
The TopRow determines the start row position at the zero position of the View.Bounds.Y.

Yep, just figured that out last night with https://github.com/migueldeicaza/gui.cs/issues/1404#issuecomment-889678443

Apologies if I'm getting slightly off-topic here -- I hope to be done soon and can share example result + code when everything seems good and maybe someone will find it useful for a similar use-case.

Anyways one thing I can't figure out: What is the correct way to manually add a new line to `TextView.Text`? Say if the `TextView` is readonly.

Using the `\n` escape sequence appears to create two new lines, leaving a blank row.

**Comment by BDisp** [comment] 2021-07-30 18:50
> Anyways one thing I can't figure out: What is the correct way to manually add a new line to `TextView.Text`? Say if the `TextView` is readonly.
> 
> Using the `\n` escape sequence appears to create two new lines, leaving a blank row.

By default the `TextView` initialize with a empty line. If you want to write something without new line, just don't include the `'\n'`. If you just want to insert a new empty line of course you will have two blanks rows, the default more the one you just added.

**Comment by bureto** [comment] 2021-07-30 19:46
Sorry I must misunderstand. 
Are you saying that the TextView.Text setter defaults to automatically append text with a new line? I'm guessing not, could you please clarify?

Just to be sure I did simple test:
```
textView.Text += "a";
textView.Text += "b";
textView.Text += "c";
textView.Text += "1";
textView.Text += "2";
textView.Text += "3";
--
Output (as expected):
abc123
```

And for with new line escape sequences:
```
textView.Text += "a";
textView.Text += "b\r\n";
textView.Text += "c\n";
textView.Text += "1";
textView.Text += "2\n";
textView.Text += "3\r\n";
--
Output (not as expected):
ab

c

12

3
--
Ideally the output would be:
ab
c
12
3
```

**Comment by BDisp** [comment] 2021-07-30 20:42
> Are you saying that the TextView.Text setter defaults to automatically append text with a new line? I'm guessing not, could you please clarify?

No. I only said that the `TextView` initializes with an empty line. If in that line you insert chars without ending with the '\n' char, then no new line are appended.

To me the output is:
```
ab
c
12
3
```

**Comment by tznind** [comment] 2021-08-01 11:06
> And for with new line escape sequences: [...]

Is this using the nuget package @bureto? perhaps this is an issue that has already been solved in main.  Are you able to reproduce this in the current codebase in main @bureto

**Comment by bureto** [comment] 2021-08-01 16:31
> Is this using the nuget package @bureto? perhaps this is an issue that has already been solved in main. Are you able to reproduce this in the current codebase in main @bureto 

Great suggestion, that has fixed it for me. Thanks.

**Comment by bureto** [comment] 2021-08-01 17:38
One last thing I'd like to try is implementing this idea:

> Would it be possible to have functionality similar to CanFocus=false, except it allows scrolling and perhaps selecting/highlighting? i.e. You can focus the TextView, but the cursor remains on the previous TextView where it just was. I think for something like this would probably require a custom solution. I'm thinking it could have an invisible cursor on the newly focused readonly TextView, and draw a pseudo cursor in the box where it left off. Then a hotkey in the TopView will set focus to the previous TextView on any keypress.

It will be sort of broken looking with the current issue of TextView not maintaining `DesiredCursorVisibility`, but will still be good for my purposes I think. 

I'm not sure how to draw/insert a "pseudo-placeholder-cursor" though. My idea is to just have a static white underline cursor to show where the input will continue on focus again (so a blinking cursor is not needed which should hopefully make it simpler).

How to do such a thing, or any suggestions?

**Comment by BDisp** [comment] 2021-08-01 17:48
I have all almost all fixed. with a bunch of new features for `Visible`, `Enable` and the blinking cursor. After this changes you will see that most will work better. Please, be patient.

**Comment by BDisp** [comment] 2021-08-02 22:29
@bureto I already finished my PR #1385 where the `DesiredCursorVisibility` on the `TextView` had been fixed. It also was added others features like `Enable` property and the events `CanFocusChanged`, `EnableChanged` and the `VisibleChanged`. The `FileDialog` was also improved.

**Comment by migueldeicaza** [comment] 2021-08-03 03:44
The XtermSharp-based TerminalView has not been updated in a while, but it should not be hard to update.

It provides a pseudo-terminal and emulation of a VT100/Xterm terminal in a view, and you can either feed terminal data manually, or you can connect it directly to a subprocess that will run for you.

This is different than command line parsing which you alluded in another post.

**Closed** 2022-02-06 22:59 UTC
Labels: question
