### ISSUE TITLE
UICatalog does not render well when it is in full screen.

### ISSUE THREAD

**Issue by BDisp** [migueldeicaza/gui.cs#683] opened 2020-06-13 14:29 UTC
![full-screen1](https://user-images.githubusercontent.com/13117724/84571357-967ba880-ad8a-11ea-81fb-cb19aec42cb0.png)
![full-screen2](https://user-images.githubusercontent.com/13117724/84571358-97143f00-ad8a-11ea-93fc-77a817424dcf.png)
![full-screen3](https://user-images.githubusercontent.com/13117724/84571360-97acd580-ad8a-11ea-96c8-843198211f74.png)

**Comment by tig** [comment] 2020-06-13 17:04
I can't repro this.

**Comment by BDisp** [comment] 2020-06-13 17:09
> 
> 
> I can't repro this.

Ok. In `cmd.exe` initiate the app and maximize the window. Then double click in `Keys`, but could be other scenario. The window will be like the second picture. Then press `Ctrl+Q` to quit and the window will be like the third picture.

**Comment by tig** [comment] 2020-06-13 17:32
Is this a dupe of https://github.com/migueldeicaza/gui.cs/issues/551?

When i do this, I get different results. I don't get the ugly painting, but the view doesn't resize.

**Comment by BDisp** [comment] 2020-06-14 00:36
>  I don't get the ugly painting

It is exactly how it appears to me.

**Closed** 2020-06-16 14:07 UTC
