### ISSUE TITLE
Button.Clicked is Action and not an event?

### ISSUE THREAD

**Issue by MihaMarkic** [migueldeicaza/gui.cs#101] opened 2018-06-07 08:33 UTC
Why is Button.Clicked (and I assume other events) implemented as Action but not as an event?
I'd say event is more natural and standard.

**Comment by pmsanford** [comment] 2018-06-07 17:22
Same is true of RadioGroup.SelectionChanged but not TextField.Changed

**Comment by MihaMarkic** [comment] 2018-06-08 11:55
Should I create a PR to fix this by converting Action to EventHandler?

**Comment by migueldeicaza** [comment] 2018-06-09 12:30
I have just never appreciated EventHandler types.   They were invented in an era that lacked lambdas.   My problem with it is two fold: the first parameter is rarely used and when you need it lambdas are now available.   The second is that the payload to the event rather than being just a value is another type, this is just too much boilerplate in my view.

Am I missing something?

**Comment by pmsanford** [comment] 2018-06-09 15:55
The benefits of events as I see it are:

1. The familiarity of the pattern to people who use the .NET Framework libraries that implement events
2. The more obvious/less cumbersome way to attach and detatch multiple handlers
3. The ability to control how you store multiple handlers (by overriding the event's add and remove handlers)
4. The built in pattern of communicating things back to the caller or between different handlers

I'd say the latter three are pretty niche cases, though, at least in the context of a UI library. Personally, I don't have strong feelings either way, other than a bias for consistentcy

**Comment by ericsink** [comment] 2018-06-09 16:15
I share Miguel's scorn for events. 

That said, consistency is a good thing. Sometimes the right answer is to make things consistently awful. If so, events are the perfect way to achieve that.

**Comment by biohazard999** [comment] 2018-06-09 16:20
I feel they are as noise.

```
var btn = new Button();
btn.Click += () => Console.WriteLine("Clicked");

//VS
var btn = new Button();
btn.Click += (sender,args) => Console.WriteLine("Clicked");

//Long
var btn = new Button();
btn.Click += Clicked;

void Clicked() => Console.WriteLine("Clicked");

//VS
var btn = new Button();
btn.Click += Clicked;

void Clicked(object sender, EventArgs args) => Console.WriteLine("Clicked");
```

**Comment by MihaMarkic** [comment] 2018-06-09 18:45
There are other reasons for events instead of actions besides ones mentioned by @pmsanford.
On top of my head:
Such as converting events to Tasks or using them with Reactive stuff - I think there are utilities that handle these easily with events. Not sure about actions, but it shouldn't be hard anyway.
Also, what if I want to handle multiple buttons with a single method? I'd cast sender to button and then do whatever I'd do.

**Comment by MihaMarkic** [comment] 2018-06-10 07:43
Sure, it's doable. But is it optimal? Compiler creates a hidden class just for that.

**Comment by migueldeicaza** [comment] 2018-06-13 15:59
Good point folks - I am on vacation this week, with limited access to the internet, but will join this conversation next week.   There seem to be two issues, one of consistency (public delegate vs event) and whether the signature should be EventHandler or the newer Action/Func pattern.

Will ponder here next week.

**Comment by Slesa** [comment] 2019-05-13 21:15
Introducing events would be a lie. We do not have concurrent tasks, no UI thread in the background, no devices sending something. When it comes to the terminal, we have an endless loop, polling the keyboard and the mouse - which means essentially waiting for the user - and meanwhile doing things.

Regarding the interaction between menu and a statusbar, I'd really appreciate to use `new StatusBarMessage(menuItem.HelpText)` to *send* sth to the bar. But it doesn't feel right here.

Not sure if that somehow interferes with the reactive stuff...

**Comment by bryancostanich** [comment] 2019-09-03 20:24
FWIW, I vote for events. They're standard, a lot of libraries and things are built on top of them. And I'm not sure it's possible to remove an action. Whereas with events I can remove a handler via `-=`.

**Comment by migueldeicaza** [comment] 2019-09-23 15:08
You can remove an action by clearing it: control.Action = null

But I hear you, you want events, I need to digest this, I think I will make the change, but it will break people

**Comment by tig** [comment] 2020-05-24 04:27
Sorry I didn't see this Issue when I created this one: https://github.com/migueldeicaza/gui.cs/issues/447

I'm clearly in the `EventHandler` camp. For all the reasons above, plus: `Action` doesn't support multiple subscribers. `EventHandler` is designed to be used in a pub/sub way.

I think `Action` is awesome when used for internal-details. But for public APIs (and `Terminal.Gui` is a public API) `EventHandler` should be the norm.

**Comment by tig** [comment] 2020-06-04 04:01
Dupe of #447

**Closed by tig** 2020-06-04 04:01 UTC
Labels: design
