### ISSUE TITLE
Auto-generate IDs for controls

### ISSUE THREAD

**Issue by tmontney** [migueldeicaza/gui.cs#252] opened 2019-09-02 00:00 UTC
In order to find a control at runtime, a control needs an ID. The field is blank by default. Preferrably, the default could be the name of the local variable that initially created it (not sure if possible via Reflection). Otherwise, an optional argument for the constructor. If not specified, something predictable (Checkbox-001).

I was also surprised to see these controls didn't inherit from a base class. Perhaps some common properties that apply to all the controls could be combined into a base class, called Control (like .NET WinForms does).

**Comment by tig** [comment] 2020-06-04 04:12
I'm calling this a dupe of #538

**Closed by tig** 2020-06-04 04:12 UTC
Labels: enhancement
