### ISSUE TITLE
I want to go back to normal Console Mode after using gui.cs as a login

### ISSUE THREAD

**Issue by YamanAlhalabi** [migueldeicaza/gui.cs#240] opened 2019-08-05 19:59 UTC
I want to go back to normal Console Mode after using gui.cs as a login, and I may also need to start it again.

**Comment by migueldeicaza** [comment] 2019-08-14 20:13
I do not understand what the problem is

**Comment by oSumAtrIX** [comment] 2019-12-08 00:12
he wants to finalize/destroy the running application object and continue with the normal console

**Comment by tig** [comment] 2020-05-24 04:58
I don't understand either.

See `Application.Init` and `Application.Shutdown`.

**Comment by tig** [comment] 2020-06-04 04:07
Closing. @YamanAlhalabi if this is still a concern please reopen.

**Closed by tig** 2020-06-04 04:07 UTC
Labels: enhancement
