### ISSUE TITLE
Button.Clicked() should have a reference to the button itself as argument

### ISSUE THREAD

**Issue by fanoI** [migueldeicaza/gui.cs#57] opened 2018-02-19 08:50 UTC
This could be useful in two cases:

1. One wants to use the same Action for all buttons but needs a way to retrieve what button was clicked
2. One wants to serialize all the View, to do this it would need access to the button container and he could do this using the button's SuperView property

**Comment by migueldeicaza** [comment] 2018-02-20 17:10
I have never been a fan of that, I always thought this idiom was wasteful, and in the world of Lambdas, I figured the context was enough.

Let me ponder this a little more, perhaps being a good citizen in the land of existing expectations is what I need to do.

**Comment by fanoI** [comment] 2018-02-21 09:11
I admit that first case could be considered an anti-pattern indeed but the second case could have a good use. How do you would pass a reference to the button itself or to its SuperView using a lambda in the Clicket delegate?

**Comment by tig** [comment] 2020-06-01 03:05
Dupe of #101

**Closed by tig** 2020-06-01 03:05 UTC
Labels: design
