### ISSUE TITLE
Fill doesn't respect window frame

### ISSUE THREAD

**Issue by bryancostanich** [migueldeicaza/gui.cs#249] opened 2019-08-28 21:40 UTC
If i create a label and set the width to fill, it seems to overwrite the window frame.

this code:

```csharp
// Dynamically computed
var label = new Label("Welcome to the Meadow Provisioning tool. Brought to you by the 90s.") {
    X = 1,
    Y = 2,
    Width = Dim.Fill(),
    Height = 1
};
top.Add(label);
```

note the empty window frame token on the right:

<img width="1302" alt="Screen Shot 2019-08-28 at 2 39 49 PM" src="https://user-images.githubusercontent.com/947633/63894540-b7147680-c9a1-11e9-831e-b53f24b3cf34.png">

however, if i subtract a block, it appears correctly:

```csharp:
// Dynamically computed
var label = new Label("Welcome to the Meadow Provisioning tool. Brought to you by the 90s.") {
    X = 1,
    Y = 2,
    Width = Dim.Fill() - 1,
    Height = 1
};
top.Add(label);
```

<img width="1299" alt="Screen Shot 2019-08-28 at 2 36 57 PM" src="https://user-images.githubusercontent.com/947633/63894519-a6fc9700-c9a1-11e9-81ab-27011fb918d3.png">

Seems to me that the `Dim.Fill()` should take into account the outside frame and only return the internal bounds, no?

**Comment by tig** [comment] 2020-05-24 04:46
I can't reproduce this. Must have been fixed. Closing.

**Closed by tig** 2020-05-24 04:46 UTC
