### ISSUE TITLE
On macOS, you can scroll away from the alternate screen in which the application is being displayed

### ISSUE THREAD

**Issue by mklement0** [migueldeicaza/gui.cs#954] opened 2020-10-14 20:54 UTC
Note: This is probably just a case of _documenting_ the limitation, because it seem to be inherent to the terminal applications on macOS (even `man`'s display behaves this way).

On Windows and Linux, Terminal.Gui applications render on a separate, singe-page screen (no scroll bars shown by the terminal program) that is independent of the regular terminal screen, to which you return on exiting such an application.

On macOS, you can unexpectedly use the terminal's scroll bars to _scroll away_ from this screen, back to the previous terminal output. Seemingly just the latest "screenful" of the regular screen is overlaid with the GUI.

Example: running in iTerm.app, scrolling back up to previous terminal output while the example application is running:

![image](https://user-images.githubusercontent.com/588825/96043021-54e43280-0e3c-11eb-99d4-82dcf0025df0.png)

**Comment by BDisp** [comment] 2020-10-14 20:58
Yes it happens to me too. It's ugly :-(

**Comment by tig** [comment] 2021-03-09 19:56
By design (this is how terminals work). Closing.

**Closed by tig** 2021-03-09 19:56 UTC
Labels: bug
