### ISSUE TITLE
Mouse does not work in Windows Terminal

### ISSUE THREAD

**Issue by pviotti** [migueldeicaza/gui.cs#332] opened 2020-02-28 15:04 UTC
When executing the example projects included in the repo on PowerShell or cmd in the Windows Terminal ([this](https://www.microsoft.com/en-us/p/windows-terminal-preview/9n0dx20hk701?activetab=pivot:overviewtab), [here](https://github.com/microsoft/terminal) is the code) some anomalies happen:
 - mouse is not tracked
 - mouse click on menus does not work
 - the element of the ListView (?) overflow

![image](https://user-images.githubusercontent.com/1350095/75559260-0dd73780-5a3b-11ea-94f1-92bf4229e750.png)

OS: Windows 10 1909
Terminal.Gui version: 0.24.0 (dev)

**Comment by BDisp** [comment] 2020-02-28 17:18
I already checked and it's a very odd behavior indeed

**Comment by odalet** [comment] 2020-02-29 17:04
Same behavior when running the sample inside WSL inside Windows Terminal:
![image](https://user-images.githubusercontent.com/79333/75611704-3c2d4380-5b1d-11ea-8777-9491c8096491.png)

However, the thumb in the vertical scroll bar is correctly rendered (whereas it is not in a standard command prompt):
![image](https://user-images.githubusercontent.com/79333/75611714-4a7b5f80-5b1d-11ea-8145-8c5451ff3229.png)

Well, that may be a problem with Consolas (missing support for fallback characters?); once I change my command prompt font from Consolas to Fira Code, everything is fine:
![image](https://user-images.githubusercontent.com/79333/75611787-d1303c80-5b1d-11ea-8950-2778b647e6f7.png)

**Comment by TylerLeonhardt** [comment] 2020-03-10 05:49
Mouse support isn't supported in Windows Terminal but it's being worked on - confirmed:

https://twitter.com/cinnamon_msft/status/1237253970759782401?s=19

**Comment by tig** [comment] 2020-03-11 05:38
https://github.com/PowerShell/GraphicalTools/issues/58

**Comment by tig** [comment] 2020-05-21 02:23
Confirmed mouse is still not working in Windows Terminal 1.0 or Windows Terminal (Preview) Version: 1.0.1402.0.

**Comment by BDisp** [comment] 2020-05-21 10:23
This really is a setback.

**Comment by tig** [comment] 2020-06-13 16:14
This is the Windows Terminal bug, for clarity: https://github.com/microsoft/terminal/issues/376

**Comment by tig** [comment] 2020-12-27 21:06
Until this is fixed in Windows Terminal, there's nothing we can do about it. 

For now I vote we do NOT make this a ship-blocker for 1.0. 

I'm removing the 1.0 label. If you disagree please reply with why.

**Comment by tig** [comment] 2021-04-16 15:48
New info:

https://github.com/microsoft/terminal/issues/376#issuecomment-821263602

Supposedly if we use VT-Style mouse support this will work today.

Are we using VT-Style or Win32?  (I will try to look later today)

**Comment by BDisp** [comment] 2021-04-16 15:56
> Are we using VT-Style or Win32? (I will try to look later today)

Yes, in the `NetDriver`.

**Comment by tig** [comment] 2021-04-16 16:33
Woot. I just did UICatalog -usc and mouse works in Windows Terminal 1.7+. 

However netDriver is SO. DAMN. SLOW.

I wonder if it's possible to modify `WindowsDriver` to use VT-style mouse support while still using the console APIs for everything else?

**Comment by BDisp** [comment] 2021-04-16 16:38
> However netDriver is SO. DAMN. SLOW.

Yes, unfortunately.


> I wonder if it's possible to modify `WindowsDriver` to use VT-style mouse support while still using the console APIs for everything else?

Yes, maybe it's a possibility.

**Comment by tig** [comment] 2021-05-27 17:44
As of Windows Terminal Preview 1.9, the mouse works with WindowsDriver!

It has some minor issues (double click seems too sensitive). But separate issues should be opened for those.

Closing this.

**Closed by tig** 2021-05-27 17:44 UTC
Labels: bug

**Comment by BDisp** [comment] 2021-05-27 17:47
I saw that's working yesterday, but not mouse movement. I hope they fix that too.

**Comment by BDisp** [comment] 2021-05-27 17:55
Also the `Enter` key doesn't' work in the `NetDriver`, because they aren't exposing the `Key` property, from `ConsoleKeyInfo`. So, `Key = 0` instead of `"Enter"`. So, reading from `KeyChar = 13 '\r'`, is interpreted as `Ctrl+M`.
